FROM clojure:lein-alpine as builder

RUN apk --no-cache add \
    git \
    nodejs \
    nodejs-npm

RUN npm install -g bower stylus

WORKDIR /netrunner
COPY . .
RUN bower --allow-root install
RUN stylus src/css -o resources/public/css/
RUN lein deps

RUN lein cljsbuild once prod
RUN lein cljsbuild once dev
RUN lein compile

# permit connections from non-localhost, and we will connect from outside the container
ENV LEIN_REPL_HOST=0.0.0.0
ENTRYPOINT ["lein", "repl", ":headless", ":port", "42053"]
