FROM clojure:lein-alpine as builder

# RUN apk --no-cache add \
    # git
    # nodejs \
    # nodejs-npm

# RUN npm install -g bower stylus

WORKDIR /netrunner
COPY . .
# RUN bower --allow-root install
RUN lein deps
RUN lein compile
# TODO: This can have card edn mounted in as a volume.
ENTRYPOINT ["lein", "fetch", "--no-card-images", "--local", "."]
